### ISSUE TITLE
Registration page email field

### ISSUE THREAD

**Issue by ptwptw** [dreamfactorysoftware/javascript-sdk#1] opened 2015-10-12 06:04 UTC
The position of the email field on the sign-in page needs a tweak. It's visible but not clickable in Firefox, IE or Chrome (Windows). Maybe it's underneath the page header somehow. It can be accessed by clicking the password field and hitting shift-tab to get to the previous field.

**Comment by jstablesdf** [comment] 2015-10-12 17:57
I did a quick clone of the repository, and when I open index.html I see this:

![image](https://cloud.githubusercontent.com/assets/9806362/10434656/f0c20c28-70e8-11e5-849a-5a273dd8b3e4.png)

The Email field is click-able.

The only way I was able to reproduce the problem was to remove `styles.css` from `/add_javascript/css`

**Comment by ptwptw** [comment] 2015-10-13 02:39
Okay, that makes sense. Though while the styles.css file does exist, there's an issue with its mime type, as per below.

Firefox: 
The stylesheet [...] add_javascript/css/styles.css was not loaded because its MIME type, "text/html", is not "text/css".

IE:
SEC7113: CSS was ignored due to mime type mismatch

Chrome:
Resource interpreted as Stylesheet but transferred with MIME type text/html: 

I gather this probably means this is a server level issue (i.e. specifying allowed MIME types). (EDIT: nope, that doesn't make sense - css files are loading and working on another dreamfactory sample app with the same error (add_angular sample))

If this is the case, it's probably important to know I'm using a [myaccount].enterprise.dreamfactory.com instance and installed this code via dreamfactory apps/import/sample apps - address book for javascript.

**Comment by ptwptw** [comment] 2015-10-13 03:05
Update:
For the add_angular example I checked (as per edit note above), the css on Chrome and Firefox, but does not on IE. This seems to be because (as per error messages above), Firefox and Chrome still use the file as CSS - while IE ignores the file completely.

Assessment:
Needs to be checked further, but It seems possible this is due to MIME types config at the server level and currently affects enterprise dreamfactory.com accounts.

**Comment by ptwptw** [comment] 2015-10-13 04:05
For the record, this is what I see:

![2015-10-13_15-03-59](https://cloud.githubusercontent.com/assets/15083736/10445259/d415f70a-71bb-11e5-9e2d-b4d22cc88ea1.jpg)

**Comment by jstablesdf** [comment] 2015-10-29 14:01
We were able to avoid this issue by placing the CSS within index.html (`<style>` tags). Also this is only reproducible using sandbox instances on enterprise.dreamfactory.com, none of our locally installed instances had the problem.

**Comment by HarveyEV** [comment] 2016-03-13 23:25
I am also having this issue with the Angular Address Book sample app serving the app.css as text/html.  Inline styles is the answer? Wow. Can we fix this issue?

**Comment by drewpearce** [comment] 2016-06-08 15:29
resolved in 2.1.1

**Closed as completed by drewpearce** 2016-06-08 15:29 UTC
